apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - name: accounts
        image: javaexpress/accounts:2.0.0
        ports:
        - containerPort: 9003
        env:
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          value: http://zipkin-service:9411/api/v2/spans
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eurekaserver-service:9002/eureka/
        - name: SPRING_APPLICATION_NAME
          value: accounts
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
spec:
  selector:
    app: accounts
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003
