apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards
  template:
    metadata:
      name: cardspod      
      labels:
        app: cards
    spec:
      containers:
      - name: cards
        image: sureshsencha/cards:2.0.0
        ports:
        - containerPort: 9004
        env:
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          value: http://zipkin-service:9411/api/v2/spans
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://Eureka-Server-service:9002/eureka/
        - name: SPRING_APPLICATION_NAME
          value: cards
---
apiVersion: v1
kind: Service
metadata:
  name: cards-service
spec:
  selector:
    app: cards
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9004
      targetPort: 9004