apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loanspod
  template:
    metadata:
      labels:
        app: loanspod
    spec:
      containers:
      - name: loans
        image: sureshsencha/loans:2.0.0
        ports:
        - containerPort: 9005
        env:
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          value: http://zipkin-service:9411/api/v2/spans
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://Eureka-Server-service:9002/eureka/
        - name: SPRING_CONFIG_IMPORT
        - name: SPRING_APPLICATION_NAME
          value: loans
---
apiVersion: v1
kind: Service
metadata:
  name: loans-service
spec:
  selector:
    app: loanspod
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9005
      targetPort: 9005